name: Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti dengan 'master' jika nama branch utama Anda 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/keuangan
            git pull origin main
            docker compose -f docker-compose.prod.yml up -d --build
            docker system prune -f
